// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: gateway/proto/v1/hive.proto

package hivev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeController_Ping_FullMethodName         = "/v1.NodeController/Ping"
	NodeController_DeployAgent_FullMethodName  = "/v1.NodeController/DeployAgent"
	NodeController_StopAgent_FullMethodName    = "/v1.NodeController/StopAgent"
	NodeController_GetNodeState_FullMethodName = "/v1.NodeController/GetNodeState"
)

// NodeControllerClient is the client API for NodeController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeController defines the sync-control interface between Mac (Manager) and Linux (Core).
// Transport: gRPC + mTLS
type NodeControllerClient interface {
	// Ping checks readiness and latency
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// DeployAgent instructs the node to spawn a new agent container
	DeployAgent(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
	// StopAgent halts an agent execution
	StopAgent(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// GetNodeState retrieves full snapshot of the node (resources, running pods)
	GetNodeState(ctx context.Context, in *NodeStateRequest, opts ...grpc.CallOption) (*NodeStateResponse, error)
}

type nodeControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControllerClient(cc grpc.ClientConnInterface) NodeControllerClient {
	return &nodeControllerClient{cc}
}

func (c *nodeControllerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NodeController_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControllerClient) DeployAgent(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, NodeController_DeployAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControllerClient) StopAgent(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, NodeController_StopAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControllerClient) GetNodeState(ctx context.Context, in *NodeStateRequest, opts ...grpc.CallOption) (*NodeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStateResponse)
	err := c.cc.Invoke(ctx, NodeController_GetNodeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeControllerServer is the server API for NodeController service.
// All implementations must embed UnimplementedNodeControllerServer
// for forward compatibility.
//
// NodeController defines the sync-control interface between Mac (Manager) and Linux (Core).
// Transport: gRPC + mTLS
type NodeControllerServer interface {
	// Ping checks readiness and latency
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// DeployAgent instructs the node to spawn a new agent container
	DeployAgent(context.Context, *DeployRequest) (*DeployResponse, error)
	// StopAgent halts an agent execution
	StopAgent(context.Context, *StopRequest) (*StopResponse, error)
	// GetNodeState retrieves full snapshot of the node (resources, running pods)
	GetNodeState(context.Context, *NodeStateRequest) (*NodeStateResponse, error)
	mustEmbedUnimplementedNodeControllerServer()
}

// UnimplementedNodeControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControllerServer struct{}

func (UnimplementedNodeControllerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeControllerServer) DeployAgent(context.Context, *DeployRequest) (*DeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployAgent not implemented")
}
func (UnimplementedNodeControllerServer) StopAgent(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAgent not implemented")
}
func (UnimplementedNodeControllerServer) GetNodeState(context.Context, *NodeStateRequest) (*NodeStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeState not implemented")
}
func (UnimplementedNodeControllerServer) mustEmbedUnimplementedNodeControllerServer() {}
func (UnimplementedNodeControllerServer) testEmbeddedByValue()                        {}

// UnsafeNodeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControllerServer will
// result in compilation errors.
type UnsafeNodeControllerServer interface {
	mustEmbedUnimplementedNodeControllerServer()
}

func RegisterNodeControllerServer(s grpc.ServiceRegistrar, srv NodeControllerServer) {
	// If the following call panics, it indicates UnimplementedNodeControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeController_ServiceDesc, srv)
}

func _NodeController_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControllerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeController_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControllerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeController_DeployAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControllerServer).DeployAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeController_DeployAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControllerServer).DeployAgent(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeController_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControllerServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeController_StopAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControllerServer).StopAgent(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeController_GetNodeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControllerServer).GetNodeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeController_GetNodeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControllerServer).GetNodeState(ctx, req.(*NodeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeController_ServiceDesc is the grpc.ServiceDesc for NodeController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NodeController",
	HandlerType: (*NodeControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _NodeController_Ping_Handler,
		},
		{
			MethodName: "DeployAgent",
			Handler:    _NodeController_DeployAgent_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _NodeController_StopAgent_Handler,
		},
		{
			MethodName: "GetNodeState",
			Handler:    _NodeController_GetNodeState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/proto/v1/hive.proto",
}
