// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gateway/proto/v1/hive.proto

package hivev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // e.g. "mac-manager-01"
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "ready", "draining", "busy"
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Spec          *AgentSpec             `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{2}
}

func (x *DeployRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeployRequest) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type AgentSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`       // e.g. "agent-alpha-01"
	Role      string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                            // "coder", "architect", "ceo"
	ModelTier string                 `protobuf:"bytes,3,opt,name=model_tier,json=modelTier,proto3" json:"model_tier,omitempty"` // "tier-1", "tier-2"
	EnvVars   []string               `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`       // "KEY=VALUE"
	// Resource constraints
	Resources *ResourceLimit `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	// Security
	NetworkEnabled bool `protobuf:"varint,6,opt,name=network_enabled,json=networkEnabled,proto3" json:"network_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentSpec) Reset() {
	*x = AgentSpec{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSpec) ProtoMessage() {}

func (x *AgentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSpec.ProtoReflect.Descriptor instead.
func (*AgentSpec) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{3}
}

func (x *AgentSpec) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentSpec) GetModelTier() string {
	if x != nil {
		return x.ModelTier
	}
	return ""
}

func (x *AgentSpec) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *AgentSpec) GetResources() *ResourceLimit {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AgentSpec) GetNetworkEnabled() bool {
	if x != nil {
		return x.NetworkEnabled
	}
	return false
}

type ResourceLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float32                `protobuf:"fixed32,1,opt,name=cpu,proto3" json:"cpu,omitempty"`      // Cores
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"` // MB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimit) Reset() {
	*x = ResourceLimit{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimit) ProtoMessage() {}

func (x *ResourceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimit.ProtoReflect.Descriptor instead.
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceLimit) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceLimit) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "starting", "failed"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{5}
}

func (x *DeployResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DeployResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeployResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NodeStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStateRequest) Reset() {
	*x = NodeStateRequest{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStateRequest) ProtoMessage() {}

func (x *NodeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStateRequest.ProtoReflect.Descriptor instead.
func (*NodeStateRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{8}
}

type NodeStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	ActiveAgents  []*AgentSummary        `protobuf:"bytes,4,rep,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStateResponse) Reset() {
	*x = NodeStateResponse{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStateResponse) ProtoMessage() {}

func (x *NodeStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStateResponse.ProtoReflect.Descriptor instead.
func (*NodeStateResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{9}
}

func (x *NodeStateResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStateResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeStateResponse) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *NodeStateResponse) GetActiveAgents() []*AgentSummary {
	if x != nil {
		return x.ActiveAgents
	}
	return nil
}

type AgentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSummary) Reset() {
	*x = AgentSummary{}
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSummary) ProtoMessage() {}

func (x *AgentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_v1_hive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSummary.ProtoReflect.Descriptor instead.
func (*AgentSummary) Descriptor() ([]byte, []int) {
	return file_gateway_proto_v1_hive_proto_rawDescGZIP(), []int{10}
}

func (x *AgentSummary) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentSummary) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_gateway_proto_v1_hive_proto protoreflect.FileDescriptor

const file_gateway_proto_v1_hive_proto_rawDesc = "" +
	"\n" +
	"\x1bgateway/proto/v1/hive.proto\x12\x02v1\"H\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"`\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\"Q\n" +
	"\rDeployRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\x04spec\x18\x02 \x01(\v2\r.v1.AgentSpecR\x04spec\"\xce\x01\n" +
	"\tAgentSpec\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"model_tier\x18\x03 \x01(\tR\tmodelTier\x12\x19\n" +
	"\benv_vars\x18\x04 \x03(\tR\aenvVars\x12/\n" +
	"\tresources\x18\x05 \x01(\v2\x11.v1.ResourceLimitR\tresources\x12'\n" +
	"\x0fnetwork_enabled\x18\x06 \x01(\bR\x0enetworkEnabled\"9\n" +
	"\rResourceLimit\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x02R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\"p\n" +
	"\x0eDeployResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\">\n" +
	"\vStopRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10NodeStateRequest\"\x9d\x01\n" +
	"\x11NodeStateResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x02R\bramUsage\x125\n" +
	"\ractive_agents\x18\x04 \x03(\v2\x10.v1.AgentSummaryR\factiveAgents\"h\n" +
	"\fAgentSummary\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds2\xde\x01\n" +
	"\x0eNodeController\x12)\n" +
	"\x04Ping\x12\x0f.v1.PingRequest\x1a\x10.v1.PingResponse\x124\n" +
	"\vDeployAgent\x12\x11.v1.DeployRequest\x1a\x12.v1.DeployResponse\x12.\n" +
	"\tStopAgent\x12\x0f.v1.StopRequest\x1a\x10.v1.StopResponse\x12;\n" +
	"\fGetNodeState\x12\x14.v1.NodeStateRequest\x1a\x15.v1.NodeStateResponseB6Z4github.com/winds18/vibecraft/gateway/proto/v1;hivev1b\x06proto3"

var (
	file_gateway_proto_v1_hive_proto_rawDescOnce sync.Once
	file_gateway_proto_v1_hive_proto_rawDescData []byte
)

func file_gateway_proto_v1_hive_proto_rawDescGZIP() []byte {
	file_gateway_proto_v1_hive_proto_rawDescOnce.Do(func() {
		file_gateway_proto_v1_hive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_v1_hive_proto_rawDesc), len(file_gateway_proto_v1_hive_proto_rawDesc)))
	})
	return file_gateway_proto_v1_hive_proto_rawDescData
}

var file_gateway_proto_v1_hive_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gateway_proto_v1_hive_proto_goTypes = []any{
	(*PingRequest)(nil),       // 0: v1.PingRequest
	(*PingResponse)(nil),      // 1: v1.PingResponse
	(*DeployRequest)(nil),     // 2: v1.DeployRequest
	(*AgentSpec)(nil),         // 3: v1.AgentSpec
	(*ResourceLimit)(nil),     // 4: v1.ResourceLimit
	(*DeployResponse)(nil),    // 5: v1.DeployResponse
	(*StopRequest)(nil),       // 6: v1.StopRequest
	(*StopResponse)(nil),      // 7: v1.StopResponse
	(*NodeStateRequest)(nil),  // 8: v1.NodeStateRequest
	(*NodeStateResponse)(nil), // 9: v1.NodeStateResponse
	(*AgentSummary)(nil),      // 10: v1.AgentSummary
}
var file_gateway_proto_v1_hive_proto_depIdxs = []int32{
	3,  // 0: v1.DeployRequest.spec:type_name -> v1.AgentSpec
	4,  // 1: v1.AgentSpec.resources:type_name -> v1.ResourceLimit
	10, // 2: v1.NodeStateResponse.active_agents:type_name -> v1.AgentSummary
	0,  // 3: v1.NodeController.Ping:input_type -> v1.PingRequest
	2,  // 4: v1.NodeController.DeployAgent:input_type -> v1.DeployRequest
	6,  // 5: v1.NodeController.StopAgent:input_type -> v1.StopRequest
	8,  // 6: v1.NodeController.GetNodeState:input_type -> v1.NodeStateRequest
	1,  // 7: v1.NodeController.Ping:output_type -> v1.PingResponse
	5,  // 8: v1.NodeController.DeployAgent:output_type -> v1.DeployResponse
	7,  // 9: v1.NodeController.StopAgent:output_type -> v1.StopResponse
	9,  // 10: v1.NodeController.GetNodeState:output_type -> v1.NodeStateResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_proto_v1_hive_proto_init() }
func file_gateway_proto_v1_hive_proto_init() {
	if File_gateway_proto_v1_hive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_v1_hive_proto_rawDesc), len(file_gateway_proto_v1_hive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_v1_hive_proto_goTypes,
		DependencyIndexes: file_gateway_proto_v1_hive_proto_depIdxs,
		MessageInfos:      file_gateway_proto_v1_hive_proto_msgTypes,
	}.Build()
	File_gateway_proto_v1_hive_proto = out.File
	file_gateway_proto_v1_hive_proto_goTypes = nil
	file_gateway_proto_v1_hive_proto_depIdxs = nil
}
